server:
  port: 9527

spring:
  application:
    name: gateway-9527
  cloud:
    gateway:
      discovery:        # 动态路由
        locator:
          enabled: true
      routes:
      - id: payment-routes
        uri: lb://payment
        predicates:
        - Path=/payment/**
      - id: order-routes
        uri: lb://order
        predicates:
        - Path=/order/**


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用 负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001.com/eureka,http://localhost:7002/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1
